WANDB_PROJECT=specInfer python distill/train.py \
    --model_name_or_path JackFram/llama-160m  \
    --data_path data/piqa_train.json \
    --eval_data_path data/piqa_eval.json \
    --bf16 True \
    --output_dir /data/vicuna_cip \
    --num_train_epochs 3 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "steps" \
    --eval_steps 500 \
    --save_strategy "steps" \
    --save_steps 100 \
    --save_total_limit 100 \
    --learning_rate 1e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --run_name vicuna_piqa
