WANDB_PROJECT=specInfer python distill/train.py \
    --student_model_path /data/starcoderbase-1b/ \
    --teacher_model_path /data/starcoderbase/ \
    --data_path data/rustcode_train.json \
    --eval_data_path data/rustcode_eval.json \
    --bf16 True \
    --output_dir /data/starcoder_teacher_kl_teacher_student_no-sample-grad_rust \
    --num_train_epochs 3 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "steps" \
    --eval_steps 10 \
    --save_strategy "steps" \
    --save_steps 200 \
    --save_total_limit 100 \
    --learning_rate 1e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --run_name starcoder_teacher_kl_teacher_student_no-sample-grad_rust
